### PR TITLE
Fix getRelatedKey() in BelongsToSortedMany.php

### PR DESCRIPTION
**Pull request by tonystatic**
Make it possible for belongsToSortedMany relation to work with SortableController

### CODE REVIEW

**Comment by tonystatic** [comment]
( •́ ⍨ •̀)

**Comment by boxfrommars** [comment]
@tonystatic can you explain your pull request? or provide some test case?

**Comment by tonystatic** [comment]
> @tonystatic can you explain your pull request? or provide some test case?

Yep.
You are using `getRelatedKey()` and `getForeignKey()` helper functions in `SortableController` to add validation rules for `id` and `positionEntityId` fields like this:
```php
$rules['id'] .= '|exists:' . $pivotTable . ',' . $relationObject->getRelatedKey() . ',' . $relationObject->getForeignKey() . ',' . $request->input('parentId');
$rules['positionEntityId'] .= '|exists:' . $pivotTable . ',' . $relationObject->getRelatedKey() . ',' . $relationObject->getForeignKey() . ',' . $request->input('parentId');
```

So, for the model called `User` with the relation called `roles()` (organised through the pivot table `user_role` with columns `user_id` and `role_id`) this rule should look like:
```php
'id' => 'exists:user_role,role_id,user_id,{parentId}'
```

But current implementation of `getRelatedKey()` method would return `id` instead of `role_id`, because `$relatedKey` attribute in `BelongsToMany` Laravel class contains the key name of related model (`id` from `Role` model in that case). To get the pivot key name (`role_id`) you should use `$relatedPivotKey` attribute.

**Comment by boxfrommars** [comment]
Thank you! https://github.com/boxfrommars/rutorika-sortable/releases/tag/4.7.1

**Pull request merged**
